*** empty log message ***

diff --git a/docs/paramedir b/docs/paramedir
--- a/docs/paramedir
+++ b/docs/paramedir
@@ -8,14 +8,20 @@ PARAVER_HOME=${PARAVER_HOME%/bin}
 #  echo "Please set \$PARAVER_HOME to the paramedir installation root directory"
 #  exit 1
 
-if ! [ -d ${PARAVER_HOME}/lib/paraver-kernel ] ; then
-  echo "paraver-kernel libraries not found in \$PARAVER_HOME/lib/paraver-kernel/"
-  exit 1
 
-elif ! [ -e ${PARAVER_HOME}/bin/paramedir.bin ] ; then
+if [ -d "${PARAVER_HOME}/lib/paraver-kernel" ] ; then
+  LIB_DIR=lib
+elif [ -d "${PARAVER_HOME}/lib64/paraver-kernel" ] ; then
+  LIB_DIR=lib64
+else
+  echo "paraver-kernel libraries not found in \$PARAVER_HOME/{lib,lib64}/paraver-kernel/"
+  exit 1
+fi
+
+if ! [ -e ${PARAVER_HOME}/bin/paramedir.bin ] ; then
   echo "paramedir binary not found in \$PARAVER_HOME/bin/"
   exit 1
   
 fi
 
-LD_LIBRARY_PATH=$PARAVER_HOME/lib/paraver-kernel:$PARAVER_HOME/lib/ptools_common_files/:$LD_LIBRARY_PATH $PARAVER_HOME/bin/paramedir.bin "$@"	
+LD_LIBRARY_PATH=$PARAVER_HOME/${LIB_DIR}/paraver-kernel:$PARAVER_HOME/${LIB_DIR}/ptools_common_files/:$LD_LIBRARY_PATH $PARAVER_HOME/bin/paramedir.bin "$@"	
